### ISSUE TITLE
Docker方法部署后无法进行迁移操作

### ISSUE THREAD

**Issue by FirstMelody** [Bluefissure/OtterBot#184]
Docker进行迁移时会有找不到表的报错

System check identified some issues:

WARNINGS:
?: (staticfiles.W004) The directory '/FFXIVBOT/static' in the STATICFILES_DIRS setting does not exist.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'FFXIV_DEV.ffxivbot_boss' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/FFXIVBOT/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 163, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 253, in load_label
    if self.save_obj(obj):
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 209, in save_obj
    obj.save(using=self.using)
  File "/usr/local/lib/python3.9/site-packages/django/core/serializers/base.py", line 288, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 882, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 995, in _save_table
    updated = self._do_update(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1059, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1215, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1819, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: Problem installing fixture '/FFXIVBOT/db/Boss.json': Could not load ffxivbot.Boss(pk=51): (1146, "Table 'FFXIV_DEV.ffxivbot_boss' doesn't exist")

**Comment by Bluefissure** [comment]
docker-compose 启动过吗？
`docker-compose up -d`

**Comment by FirstMelody** [comment]
是的 启动过了 web在启动的时候发现了无法连接到mysql
otterbot-web | Traceback (most recent call last):
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
otterbot-web |     self.connect()
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web |     return func(*args, **kwargs)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
otterbot-web |     self.connection = self.get_new_connection(conn_params)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web |     return func(*args, **kwargs)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
otterbot-web |     connection = Database.connect(**conn_params)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 123, in Connect
otterbot-web |     return Connection(*args, **kwargs)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
otterbot-web |     super().__init__(*args, **kwargs2)
otterbot-web | MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'db' (115)")
otterbot-web | 
otterbot-web | The above exception was the direct cause of the following exception:
otterbot-web | 
otterbot-web | Traceback (most recent call last):
otterbot-web |   File "/FFXIVBOT/manage.py", line 15, in <module>
otterbot-web |     execute_from_command_line(sys.argv)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
otterbot-web |     utility.execute()
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
otterbot-web |     self.fetch_command(subcommand).run_from_argv(self.argv)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
otterbot-web |     self.execute(*args, **cmd_options)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
otterbot-web |     output = self.handle(*args, **options)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
otterbot-web |     res = handle_func(*args, **kwargs)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 97, in handle
otterbot-web |     self.check(databases=[database])
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 475, in check
otterbot-web |     all_issues = checks.run_checks(
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
otterbot-web |     new_errors = check(app_configs=app_configs, databases=databases)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/core/checks/database.py", line 13, in check_database_backends
otterbot-web |     issues.extend(conn.validation.check(**kwargs))
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/validation.py", line 9, in check
otterbot-web |     issues.extend(self._check_sql_mode(**kwargs))
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/validation.py", line 14, in _check_sql_mode
otterbot-web |     self.connection.sql_mode & {"STRICT_TRANS_TABLES", "STRICT_ALL_TABLES"}
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
otterbot-web |     res = instance.__dict__[self.name] = self.func(instance)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 443, in sql_mode
otterbot-web |     sql_mode = self.mysql_server_data["sql_mode"]
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
otterbot-web |     res = instance.__dict__[self.name] = self.func(instance)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 399, in mysql_server_data
otterbot-web |     with self.temporary_connection() as cursor:
otterbot-web |   File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
otterbot-web |     return next(self.gen)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 694, in temporary_connection
otterbot-web |     with self.cursor() as cursor:
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web |     return func(*args, **kwargs)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
otterbot-web |     return self._cursor()
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 299, in _cursor
otterbot-web |     self.ensure_connection()
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web |     return func(*args, **kwargs)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
otterbot-web |     self.connect()
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
otterbot-web |     raise dj_exc_value.with_traceback(traceback) from exc_value
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
otterbot-web |     self.connect()
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web |     return func(*args, **kwargs)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
otterbot-web |     self.connection = self.get_new_connection(conn_params)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web |     return func(*args, **kwargs)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
otterbot-web |     connection = Database.connect(**conn_params)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 123, in Connect
otterbot-web |     return Connection(*args, **kwargs)
otterbot-web |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
otterbot-web |     super().__init__(*args, **kwargs2)
otterbot-web | django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on 'db' (115)")

**Comment by Bluefissure** [comment]
检查下 otterbot-db
`docker logs otterbot-db`

**Comment by FirstMelody** [comment]
没有看到明显异常

[root@ubuntu-server ~]# docker logs otterbot-db
2022-09-22 10:01:15+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.39-1.el7 started.
2022-09-22 10:01:16+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-09-22 10:01:16+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.39-1.el7 started.
2022-09-22 10:01:16+00:00 [Note] [Entrypoint]: Initializing database files
2022-09-22T10:01:16.305235Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2022-09-22T10:01:18.379411Z 0 [Warning] InnoDB: New log files created, LSN=45790
2022-09-22T10:01:18.946458Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2022-09-22T10:01:19.302499Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 813da922-3a5d-11ed-811f-0242ac120002.
2022-09-22T10:01:19.342950Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2022-09-22T10:01:19.762107Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
2022-09-22T10:01:19.762269Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
2022-09-22T10:01:19.762933Z 0 [Warning] CA certificate ca.pem is self signed.
2022-09-22T10:01:19.823267Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2022-09-22 10:01:36+00:00 [Note] [Entrypoint]: Database files initialized
2022-09-22 10:01:36+00:00 [Note] [Entrypoint]: Starting temporary server
2022-09-22 10:01:36+00:00 [Note] [Entrypoint]: Waiting for server startup
2022-09-22T10:01:36.434281Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2022-09-22T10:01:36.435874Z 0 [Note] mysqld (mysqld 5.7.39) starting as process 126 ...
2022-09-22T10:01:36.469268Z 0 [Note] InnoDB: PUNCH HOLE support available
2022-09-22T10:01:36.469303Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2022-09-22T10:01:36.469310Z 0 [Note] InnoDB: Uses event mutexes
2022-09-22T10:01:36.469315Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2022-09-22T10:01:36.469320Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.12
2022-09-22T10:01:36.469325Z 0 [Note] InnoDB: Using Linux native AIO
2022-09-22T10:01:36.469644Z 0 [Note] InnoDB: Number of pools: 1
2022-09-22T10:01:36.469768Z 0 [Note] InnoDB: Using CPU crc32 instructions
2022-09-22T10:01:36.471806Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2022-09-22T10:01:36.481844Z 0 [Note] InnoDB: Completed initialization of buffer pool
2022-09-22T10:01:36.484163Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2022-09-22T10:01:36.496057Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2022-09-22T10:01:36.559240Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-09-22T10:01:36.559391Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-09-22T10:01:36.802337Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-09-22T10:01:36.803898Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2022-09-22T10:01:36.803920Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2022-09-22T10:01:36.804398Z 0 [Note] InnoDB: Waiting for purge to start
2022-09-22T10:01:36.854593Z 0 [Note] InnoDB: 5.7.39 started; log sequence number 2756265
2022-09-22T10:01:36.855136Z 0 [Note] Plugin 'FEDERATED' is disabled.
2022-09-22T10:01:36.859237Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2022-09-22T10:01:36.886928Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2022-09-22T10:01:36.886958Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
2022-09-22T10:01:36.886968Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
2022-09-22T10:01:36.886990Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
2022-09-22T10:01:36.909485Z 0 [Note] InnoDB: Buffer pool(s) load completed at 220922 10:01:36
2022-09-22T10:01:37.288554Z 0 [Warning] CA certificate ca.pem is self signed.
2022-09-22T10:01:37.289714Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
2022-09-22T10:01:37.378424Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2022-09-22T10:01:37.418233Z 0 [Note] Event Scheduler: Loaded 0 events
2022-09-22T10:01:37.418605Z 0 [Note] mysqld: ready for connections.
Version: '5.7.39'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
2022-09-22 10:01:37+00:00 [Note] [Entrypoint]: Temporary server started.
'/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
2022-09-22 10:01:44+00:00 [Note] [Entrypoint]: Creating database FFXIV_DEV

2022-09-22 10:01:44+00:00 [Note] [Entrypoint]: Stopping temporary server
2022-09-22T10:01:44.768803Z 0 [Note] Giving 0 client threads a chance to die gracefully
2022-09-22T10:01:44.768836Z 0 [Note] Shutting down slave threads
2022-09-22T10:01:44.768846Z 0 [Note] Forcefully disconnecting 0 remaining clients
2022-09-22T10:01:44.768855Z 0 [Note] Event Scheduler: Purging the queue. 0 events
2022-09-22T10:01:44.768937Z 0 [Note] Binlog end
2022-09-22T10:01:44.770110Z 0 [Note] Shutting down plugin 'ngram'
2022-09-22T10:01:44.770129Z 0 [Note] Shutting down plugin 'partition'
2022-09-22T10:01:44.770135Z 0 [Note] Shutting down plugin 'BLACKHOLE'
2022-09-22T10:01:44.770141Z 0 [Note] Shutting down plugin 'ARCHIVE'
2022-09-22T10:01:44.770146Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
2022-09-22T10:01:44.770216Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
2022-09-22T10:01:44.770226Z 0 [Note] Shutting down plugin 'MyISAM'
2022-09-22T10:01:44.770237Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
2022-09-22T10:01:44.770242Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
2022-09-22T10:01:44.770246Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
2022-09-22T10:01:44.770250Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
2022-09-22T10:01:44.770255Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
2022-09-22T10:01:44.770259Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
2022-09-22T10:01:44.770263Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
2022-09-22T10:01:44.770267Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
2022-09-22T10:01:44.770294Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
2022-09-22T10:01:44.770319Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
2022-09-22T10:01:44.770326Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
2022-09-22T10:01:44.770331Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
2022-09-22T10:01:44.770335Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
2022-09-22T10:01:44.770339Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
2022-09-22T10:01:44.770344Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
2022-09-22T10:01:44.770348Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
2022-09-22T10:01:44.770352Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
2022-09-22T10:01:44.770356Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
2022-09-22T10:01:44.770360Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
2022-09-22T10:01:44.770365Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
2022-09-22T10:01:44.770369Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
2022-09-22T10:01:44.770373Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
2022-09-22T10:01:44.770377Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
2022-09-22T10:01:44.770406Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
2022-09-22T10:01:44.770411Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
2022-09-22T10:01:44.770415Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
2022-09-22T10:01:44.770420Z 0 [Note] Shutting down plugin 'INNODB_CMP'
2022-09-22T10:01:44.770424Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
2022-09-22T10:01:44.770429Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
2022-09-22T10:01:44.770433Z 0 [Note] Shutting down plugin 'INNODB_TRX'
2022-09-22T10:01:44.770437Z 0 [Note] Shutting down plugin 'InnoDB'
2022-09-22T10:01:44.770522Z 0 [Note] InnoDB: FTS optimize thread exiting.
2022-09-22T10:01:44.770779Z 0 [Note] InnoDB: Starting shutdown...
2022-09-22T10:01:44.871073Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2022-09-22T10:01:44.871422Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 220922 10:01:44
2022-09-22T10:01:47.591847Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12140906
2022-09-22T10:01:47.594328Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2022-09-22T10:01:47.594351Z 0 [Note] Shutting down plugin 'MEMORY'
2022-09-22T10:01:47.594361Z 0 [Note] Shutting down plugin 'CSV'
2022-09-22T10:01:47.594367Z 0 [Note] Shutting down plugin 'sha256_password'
2022-09-22T10:01:47.594371Z 0 [Note] Shutting down plugin 'mysql_native_password'
2022-09-22T10:01:47.594503Z 0 [Note] Shutting down plugin 'binlog'
2022-09-22T10:01:47.597002Z 0 [Note] mysqld: Shutdown complete

2022-09-22 10:01:47+00:00 [Note] [Entrypoint]: Temporary server stopped

2022-09-22 10:01:47+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.

2022-09-22T10:01:47.973035Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2022-09-22T10:01:47.974640Z 0 [Note] mysqld (mysqld 5.7.39) starting as process 1 ...
2022-09-22T10:01:47.978931Z 0 [Note] InnoDB: PUNCH HOLE support available
2022-09-22T10:01:47.979028Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2022-09-22T10:01:47.979068Z 0 [Note] InnoDB: Uses event mutexes
2022-09-22T10:01:47.979108Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2022-09-22T10:01:47.979148Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.12
2022-09-22T10:01:47.979234Z 0 [Note] InnoDB: Using Linux native AIO
2022-09-22T10:01:47.979694Z 0 [Note] InnoDB: Number of pools: 1
2022-09-22T10:01:47.980170Z 0 [Note] InnoDB: Using CPU crc32 instructions
2022-09-22T10:01:47.982666Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2022-09-22T10:01:47.992504Z 0 [Note] InnoDB: Completed initialization of buffer pool
2022-09-22T10:01:47.995589Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2022-09-22T10:01:48.007601Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2022-09-22T10:01:48.083824Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-09-22T10:01:48.084550Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-09-22T10:01:48.323962Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-09-22T10:01:48.325655Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2022-09-22T10:01:48.325678Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2022-09-22T10:01:48.326184Z 0 [Note] InnoDB: Waiting for purge to start
2022-09-22T10:01:48.376390Z 0 [Note] InnoDB: 5.7.39 started; log sequence number 12140906
2022-09-22T10:01:48.376869Z 0 [Note] Plugin 'FEDERATED' is disabled.
2022-09-22T10:01:48.377638Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2022-09-22T10:01:48.384205Z 0 [Note] InnoDB: Buffer pool(s) load completed at 220922 10:01:48
2022-09-22T10:01:48.387283Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2022-09-22T10:01:48.387306Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
2022-09-22T10:01:48.387314Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
2022-09-22T10:01:48.387318Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
2022-09-22T10:01:48.388502Z 0 [Warning] CA certificate ca.pem is self signed.
2022-09-22T10:01:48.388577Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
2022-09-22T10:01:48.389192Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2022-09-22T10:01:48.413100Z 0 [Note] IPv6 is available.
2022-09-22T10:01:48.413130Z 0 [Note]   - '::' resolves to '::';
2022-09-22T10:01:48.413166Z 0 [Note] Server socket created on IP: '::'.
2022-09-22T10:01:48.457436Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2022-09-22T10:01:48.472055Z 0 [Note] Event Scheduler: Loaded 0 events
2022-09-22T10:01:48.472450Z 0 [Note] mysqld: ready for connections.
Version: '5.7.39'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)

**Comment by Bluefissure** [comment]
请等待 https://github.com/Bluefissure/OtterBot/actions/runs/3107035841/jobs/5034656551 构建完成后重新拉取。

**Comment by FirstMelody** [comment]
最新构建拉取后问题解决,感谢！
