### ISSUE TITLE
not fully support mirai & a report of using tata in mirai bot

### ISSUE THREAD

**Issue by LittleNightmare** [Bluefissure/OtterBot#70]
### issue
用mirai的cqhttpmirai连接会被识别成酷q的bot版本

#### 环境
ubuntu docker，[MiraiOK](https://github.com/LXY1226/MiraiOK)，和[CQHTTPMirai](https://github.com/yyuueexxiinngg/cqhttp-mirai)
#### 问题
1. CQHTTPMirai不支持图片发送给用户
2. 用 `screen -S`挂起进程出现了离线状况，ssh连接检查发现重新上线但指令无响应，私聊bot也没有接收到，正在尝试复现问题
3. 在用户层面，目前指令测试的几个中，除了/image,/cat等发送图片外，只有私聊的/help出现问题，但可能是QQ屏蔽了
4. /bot update应该是不支持，看见后台报错了`[ERROR] [CQHTTPMirai] 未知CQHTTP API: _get_friend_list
`
##### 关于个人测试选择
使用不完善的CQHTTPMirai主要是两个原因
1. 獭獭看起来不兼容[mirai-api-http](https://github.com/project-mirai/mirai-api-http)
2. [mirai-native](https://github.com/iTXTech/mirai-native)确实可以兼容cqhttp，但只能运行在windows系统，与我想使用linux的意愿违背

~~如果不想用pro，但还想发图，且在windows运行酷q的可以考虑考虑mirai~~
~~毕竟天天笑话和涩图~~

**Comment by Bluefissure** [comment]
## Re: 问题
首先獭獭并没有在Mirai上进行测试，出现问题是意料之内（趴）
1. 我不清楚是不是CQHTTPMirai的问题，但是目前獭獭的图片有很多种发送方式，发送的方式包括CQ码和json数组，图片内容包括url也包括base64。虽然其中的一些为了兼容 [tomon](https://beta.tomon.co/) 机器人进行过一定的简化但是估计也有很多不支持的格式，需要做一些转换。
2. 可能要结合插件后台的日志来排查。
3. QQ老屏蔽怪了。
4. 大概是这个接口并没被CQHTTPMirai支持。

## 下一步开发计划
下一步可能会先着手于 [dev branch](https://github.com/Bluefissure/FFXIVBOT/tree/dev) 的重构，将狒狒14的功能和机器人领养/管理相关功能解耦一下，同时也将多平台、多插件、多协议的通信封装一下。
但是也欢迎对当前的master branch进行CQHTTPMirai相关适配的PR（如果有人愿意处理 [consumers.py](https://github.com/Bluefissure/FFXIVBOT/blob/master/ffxivbot/consumers.py) 和 [pika_rabbit.py](https://github.com/Bluefissure/FFXIVBOT/blob/master/ffxivbot/pika_rabbit.py) 这两坨shi的话），测试没问题的话会进行merge。

**Comment by LittleNightmare** [comment]
# Re: RE: 问题
忘记注明了，这个发送图片的接口的确没有被支持，并不是獭獭的问题。（但根据我的后台来看，发送图片失败是下载图片时提示403，有点迷惑
```Java

 22:28:25 [INFO] [BOT 2582367563] [群名字(xxxxxxxxx群号)] 我的QQ名字(qq号) -> [mirai:source:402,-447060305]/image 獭爹笑话
 22:28:26 [ERROR] [CQHTTPMirai] java.io.IOException: Server returned HTTP response code: 403 for URL: https://vip1.loli.net/2020/04/28/fw5tUWsiLvHAzRY.png
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at net.mamoe.mirai.utils.FileCacheStrategy$TempCache.newImageCache(FileCacheStrategy.jvm.kt:183)
        at net.mamoe.mirai.utils.FileCacheStrategy$PlatformDefault.newImageCache(FileCacheStrategy.jvm.kt)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput$init$3.invokeSuspend(DeferredReusableInput.jvm.kt:27)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput$init$3.invoke(DeferredReusableInput.jvm.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput.init(DeferredReusableInput.jvm.kt:19)
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.uploadImage(GroupImpl.kt:403)
        at net.mamoe.mirai.utils.ExternalImageKt.upload(ExternalImage.kt:106)
        at net.mamoe.mirai.message.SendImageUtilsJvmKt.uploadAsImage(SendImageUtilsJvm.kt:95)
        at tech.mihoyo.mirai.util.CQMessgeParserKt$convertToMiraiMessage$$inlined$with$lambda$2.invokeSuspend(CQMessgeParser.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

## 附加问题
我停止发送指令的一段时间后。。bot与獭窝断开连接，重连提示502，不清楚问题，之前发送的地址是`ws://xn--v9x.net:80/ws`
我打算后面再加个`/`试试
cqhttpmirai的断线重连似乎只会尝试一次，我一会写个issue提交过去
